Added basic build instructions
clearlinux/bundle-chroot-builder pull request #13
Opened 2017-11-21 20:59 UTC by mdhorn

Add the basic steps for building and installing this project.

Signed-off-by: Mark Horn <mark.d.horn@intel.com>

2017-12-08 01:19 UTC, cmarcelo commented
@tmarcu ^

2018-01-04 00:32 UTC, tmarcu requested changes

2018-01-04 00:32 UTC, tmarcu commented on README
> +    # Defaults to /usr/local or specifc --prefix=/usr
s/specifc/specific

2018-01-04 00:42 UTC, mdhorn commented
@tmarcu updated

2018-01-04 18:15 UTC, tmarcu approved these changes

2018-01-04 18:15 UTC, merged